<?php

//Listar Nivel Educativo
function ListarDatos($FOIN_ID){
    try{
        $resultados = array();
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "SELECT ACADEMICO.ASPIRANTE.ASPI_ID, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID, GENERAL.TIPODOCUMENTOGENERAL.TIDG_DESCRIPCION, ACADEMICO.ASPIRANTE.ASPI_NUMERODOCUMENTO, ACADEMICO.ASPIRANTE.ASPI_PRIMERAPELLIDO, ACADEMICO.ASPIRANTE.ASPI_SEGUNDOAPELLIDO, ACADEMICO.ASPIRANTE.ASPI_PRIMERNOMBRE, ACADEMICO.ASPIRANTE.ASPI_SEGUNDONOMBRE, ACADEMICO.ASPIRANTE.ASPI_SEXO, GENERAL.ESTADOCIVILGENERAL.ESCG_DESCRIPCION, ACADEMICO.ASPIRANTE.ASPI_FECHANACIMIENTO, GENERAL.PAISGENERAL.PAGE_NOMBRE, GENERAL.DEPARTAMENTOGENERAL.DEGE_NOMBRE, GENERAL.CIUDADGENERAL.CIGE_NOMBRE, ACADEMICO.INFORMACIONSOCIOECONOMICA.INSO_ESTRATO, ACADEMICO.OTROMEDIODIVULGACION.OMED_DESCRIPCION, ACADEMICO.ASPIRANTE.ASPI_TELEFONORESIDENCIA, ACADEMICO.ASPIRANTE.ASPI_TELEFONOCELULAR, ACADEMICO.ASPIRANTE.ASPI_EMAIL, ACADEMICO.ESTUDIOSSECUNDARIOS.ESSE_FECHATERMINACION, ACADEMICO.ESTUDIOSSECUNDARIOS.ESSE_SNP, ACADEMICO.ESTUDIOSSECUNDARIOS.ESSE_FECHAPRESENTOPRUEBAS,ACADEMICO.ESTUDIOSSECUNDARIOS.ESSE_PUNTAJEOBTENIDO, ACADEMICO.INSTITUCION.INST_NOMBREINSTITUCION FROM ((((GENERAL.CIUDADGENERAL RIGHT JOIN (GENERAL.DEPARTAMENTOGENERAL RIGHT JOIN (GENERAL.PAISGENERAL RIGHT JOIN (GENERAL.ESTADOCIVILGENERAL RIGHT JOIN (GENERAL.TIPODOCUMENTOGENERAL INNER JOIN (ACADEMICO.INFORMACIONSOCIOECONOMICA RIGHT JOIN (ACADEMICO.FORMULARIOINSCRIPCION INNER JOIN ACADEMICO.ASPIRANTE ON ACADEMICO.FORMULARIOINSCRIPCION.ASPI_ID = ACADEMICO.ASPIRANTE.ASPI_ID) ON ACADEMICO.INFORMACIONSOCIOECONOMICA.ASPI_ID = ACADEMICO.ASPIRANTE.ASPI_ID) ON GENERAL.TIPODOCUMENTOGENERAL.TIDG_ID = ACADEMICO.ASPIRANTE.ASPI_TIPODOCUMENTO) ON GENERAL.ESTADOCIVILGENERAL.ESCG_ID = ACADEMICO.ASPIRANTE.ESCG_ID) ON GENERAL.PAISGENERAL.PAGE_ID = ACADEMICO.ASPIRANTE.ASPI_PAISNACIMIENTO) ON GENERAL.DEPARTAMENTOGENERAL.DEGE_ID = ACADEMICO.ASPIRANTE.ASPI_DPTONACIMIENTO) ON GENERAL.CIUDADGENERAL.CIGE_ID = ACADEMICO.ASPIRANTE.ASPI_MPIONACIMIENTO) INNER JOIN ACADEMICO.MEDIODIVULGACION ON ACADEMICO.ASPIRANTE.MEDI_IDCONOCEINSTITUCION = ACADEMICO.MEDIODIVULGACION.OMED_ID) INNER JOIN ACADEMICO.OTROMEDIODIVULGACION ON ACADEMICO.MEDIODIVULGACION.OMED_ID = ACADEMICO.OTROMEDIODIVULGACION.OMED_ID) LEFT JOIN ACADEMICO.ESTUDIOSSECUNDARIOS ON ACADEMICO.FORMULARIOINSCRIPCION.ASPI_ID = ACADEMICO.ESTUDIOSSECUNDARIOS.ASPI_ID) LEFT JOIN ACADEMICO.INSTITUCION ON ACADEMICO.ESTUDIOSSECUNDARIOS.INST_CODIGOSNP = ACADEMICO.INSTITUCION.INST_CODIGOSNP WHERE (((ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID)=".$FOIN_ID."))";
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        while (OCIFetch($query))
        {
            $fila = array(
                "TIDG_DESCRIPCION" => ociresult($query, "TIDG_DESCRIPCION"),
                "ASPI_NUMERODOCUMENTO" => ociresult($query, "ASPI_NUMERODOCUMENTO"),
                "ASPI_PRIMERAPELLIDO" => ociresult($query, "ASPI_PRIMERAPELLIDO"),
                "ASPI_SEGUNDOAPELLIDO" => ociresult($query, "ASPI_SEGUNDOAPELLIDO"),
                "ASPI_PRIMERNOMBRE" => ociresult($query, "ASPI_PRIMERNOMBRE"),
                "ASPI_SEGUNDONOMBRE" => ociresult($query, "ASPI_SEGUNDONOMBRE"),
                "ASPI_SEXO" => ociresult($query, "ASPI_SEXO"),
                "ESCG_DESCRIPCION" => ociresult($query, "ESCG_DESCRIPCION"),
                "ASPI_FECHANACIMIENTO" => ociresult($query, "ASPI_FECHANACIMIENTO"),
                "PAGE_NOMBRE" => ociresult($query, "PAGE_NOMBRE"),
                "DEGE_NOMBRE" => ociresult($query, "DEGE_NOMBRE"),
                "CIGE_NOMBRE" => ociresult($query, "CIGE_NOMBRE"),
                "INSO_ESTRATO" => ociresult($query, "INSO_ESTRATO"),
                "OMED_DESCRIPCION" => ociresult($query, "OMED_DESCRIPCION"),
                "ASPI_TELEFONORESIDENCIA" => ociresult($query, "ASPI_TELEFONORESIDENCIA"),
                "ASPI_TELEFONOCELULAR" => ociresult($query, "ASPI_TELEFONOCELULAR"),
                "ASPI_EMAIL" => ociresult($query, "ASPI_EMAIL"),
                "ESSE_FECHATERMINACION" => ociresult($query, "ESSE_FECHATERMINACION"),
                "INST_NOMBREINSTITUCION" => ociresult($query, "INST_NOMBREINSTITUCION"),
                "ESSE_SNP" => ociresult($query, "ESSE_SNP"),
                "ESSE_PUNTAJEOBTENIDO" => ociresult($query, "ESSE_PUNTAJEOBTENIDO"),
                "ESSE_FECHAPRESENTOPRUEBAS" => ociresult($query, "ESSE_FECHAPRESENTOPRUEBAS")
            );
            array_push($resultados, $fila);
        }

        echo '{"datos": ' . json_encode($resultados) . '}';

        OCILogoff($conn);

    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }

}

function ListarUbicacion($FOIN_ID){
    try{
        $resultados = array();
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "SELECT ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID, GENERAL.PAISGENERAL.PAGE_NOMBRE, GENERAL.DEPARTAMENTOGENERAL.DEGE_NOMBRE, GENERAL.CIUDADGENERAL.CIGE_NOMBRE FROM GENERAL.CIUDADGENERAL RIGHT JOIN (GENERAL.DEPARTAMENTOGENERAL RIGHT JOIN (GENERAL.PAISGENERAL RIGHT JOIN (ACADEMICO.ASPIRANTE INNER JOIN ACADEMICO.FORMULARIOINSCRIPCION ON ACADEMICO.ASPIRANTE.ASPI_ID = ACADEMICO.FORMULARIOINSCRIPCION.ASPI_ID) ON GENERAL.PAISGENERAL.PAGE_ID = ACADEMICO.ASPIRANTE.ASPI_PAISRESIDENCIA) ON GENERAL.DEPARTAMENTOGENERAL.DEGE_ID = ACADEMICO.ASPIRANTE.ASPI_DPTORESIDENCIA) ON GENERAL.CIUDADGENERAL.CIGE_ID = ACADEMICO.ASPIRANTE.ASPI_MPIORESIDENCIA WHERE (((ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID)=".$FOIN_ID."))";
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        while (OCIFetch($query))
        {
            $fila = array(
                "PAGE_NOMBRE" => ociresult($query, "PAGE_NOMBRE"),
                "DEGE_NOMBRE" => ociresult($query, "DEGE_NOMBRE"),
                "CIGE_NOMBRE" => ociresult($query, "CIGE_NOMBRE")
            );
            array_push($resultados, $fila);
        }

        echo '{"datos": ' . json_encode($resultados) . '}';

        OCILogoff($conn);

    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }

}

function ListarProgramas($FOIN_ID){
    try{
        $resultados = array();
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "SELECT ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID, ACADEMICO.PROGRAMA.PROG_NOMBRE, ACADEMICO.JORNADANEW.JORN_DESCRIPCION FROM (((ACADEMICO.PROGRAMAXFORMULARIO INNER JOIN ACADEMICO.FORMULARIOINSCRIPCION ON ACADEMICO.PROGRAMAXFORMULARIO.FOIN_ID = ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID) INNER JOIN ACADEMICO.UNIDADPROGRAMA ON ACADEMICO.PROGRAMAXFORMULARIO.UNPR_ID = ACADEMICO.UNIDADPROGRAMA.UNPR_ID) INNER JOIN ACADEMICO.PROGRAMA ON ACADEMICO.UNIDADPROGRAMA.PROG_ID = ACADEMICO.PROGRAMA.PROG_ID) LEFT JOIN ACADEMICO.JORNADANEW ON ACADEMICO.PROGRAMAXFORMULARIO.JORN_ID = ACADEMICO.JORNADANEW.JORN_ID WHERE (((ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID)=".$FOIN_ID.")) ORDER BY ACADEMICO.PROGRAMAXFORMULARIO.PRXF_PRIORIDAD";
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        while (OCIFetch($query))
        {
            $fila = array(
                "PROG_NOMBRE" => ociresult($query, "PROG_NOMBRE"),
                "JORN_DESCRIPCION" => ociresult($query, "JORN_DESCRIPCION")
            );
            array_push($resultados, $fila);
        }

        echo '{"datos": ' . json_encode($resultados) . '}';

        OCILogoff($conn);

    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }

}