<?php
//Buscar existe aspirante
function ListarInscritos(){
    try{
        $resultados = array();
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "SELECT ACADEMICO.ASPIRANTE.ASPI_ID, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID, ACADEMICO.ASPIRANTE.ASPI_NUMERODOCUMENTO,ACADEMICO.ASPIRANTE.ASPI_PRIMERAPELLIDO||' '|| ACADEMICO.ASPIRANTE.ASPI_SEGUNDOAPELLIDO ||' '|| ACADEMICO.ASPIRANTE.ASPI_PRIMERNOMBRE ||' '|| ACADEMICO.ASPIRANTE.ASPI_SEGUNDONOMBRE as NOMBRE, ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ESTADOADMISION, ACADEMICO.PROGRAMA.PROG_ID, ACADEMICO.PROGRAMA.PROG_NOMBRE, ACADEMICO.METODOLOGIA.METO_DESCRIPCION, ACADEMICO.PROGRAMAXFORMULARIO.PRXF_PRIORIDAD, ACADEMICO.JORNADANEW.JORN_DESCRIPCION, ACADEMICO.PERIODOUNIVERSIDAD.PEUN_ANO, ACADEMICO.PERIODOUNIVERSIDAD.PEUN_PERIODO FROM (((ACADEMICO.CONVOCATORIAINSCRIPCION INNER JOIN (ACADEMICO.CIRCUNSCRIPCION INNER JOIN ACADEMICO.CIRCUNSCRIPCIONXUNIDADPROGRAMA ON ACADEMICO.CIRCUNSCRIPCION.CIRC_ID = ACADEMICO.CIRCUNSCRIPCIONXUNIDADPROGRAMA.CIRC_ID) ON ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ID = ACADEMICO.CIRCUNSCRIPCIONXUNIDADPROGRAMA.COIN_ID) INNER JOIN ((((((ACADEMICO.PROGRAMAXFORMULARIO INNER JOIN ACADEMICO.FORMULARIOINSCRIPCION ON ACADEMICO.PROGRAMAXFORMULARIO.FOIN_ID = ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID) INNER JOIN ACADEMICO.ASPIRANTE ON ACADEMICO.FORMULARIOINSCRIPCION.ASPI_ID = ACADEMICO.ASPIRANTE.ASPI_ID) INNER JOIN ACADEMICO.UNIDADPROGRAMA ON ACADEMICO.PROGRAMAXFORMULARIO.UNPR_ID = ACADEMICO.UNIDADPROGRAMA.UNPR_ID) INNER JOIN ACADEMICO.PROGRAMA ON ACADEMICO.UNIDADPROGRAMA.PROG_ID = ACADEMICO.PROGRAMA.PROG_ID) INNER JOIN ACADEMICO.SERVICIOPERIODO ON ACADEMICO.FORMULARIOINSCRIPCION.SEPE_ID = ACADEMICO.SERVICIOPERIODO.SEPE_ID) INNER JOIN ACADEMICO.PERIODOUNIVERSIDAD ON ACADEMICO.SERVICIOPERIODO.PEUN_ID = ACADEMICO.PERIODOUNIVERSIDAD.PEUN_ID) ON (ACADEMICO.PERIODOUNIVERSIDAD.PEUN_ID = ACADEMICO.CONVOCATORIAINSCRIPCION.PEUN_ID) AND (ACADEMICO.CIRCUNSCRIPCION.CIRC_ID = ACADEMICO.ASPIRANTE.CIRC_ID) AND (ACADEMICO.CONVOCATORIAINSCRIPCION.UNPR_ID = ACADEMICO.UNIDADPROGRAMA.UNPR_ID)) INNER JOIN ACADEMICO.METODOLOGIA ON ACADEMICO.PROGRAMA.METO_ID = ACADEMICO.METODOLOGIA.METO_ID) INNER JOIN ACADEMICO.JORNADANEW ON ACADEMICO.PROGRAMAXFORMULARIO.JORN_ID = ACADEMICO.JORNADANEW.JORN_ID GROUP BY ACADEMICO.ASPIRANTE.ASPI_ID, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID, ACADEMICO.ASPIRANTE.ASPI_NUMERODOCUMENTO, ACADEMICO.ASPIRANTE.ASPI_PRIMERAPELLIDO, ACADEMICO.ASPIRANTE.ASPI_SEGUNDOAPELLIDO, ACADEMICO.ASPIRANTE.ASPI_PRIMERNOMBRE, ACADEMICO.ASPIRANTE.ASPI_SEGUNDONOMBRE, ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ESTADOADMISION, ACADEMICO.PROGRAMA.PROG_ID, ACADEMICO.PROGRAMA.PROG_NOMBRE, ACADEMICO.METODOLOGIA.METO_DESCRIPCION, ACADEMICO.PROGRAMAXFORMULARIO.PRXF_PRIORIDAD, ACADEMICO.JORNADANEW.JORN_DESCRIPCION, ACADEMICO.PERIODOUNIVERSIDAD.PEUN_ANO, ACADEMICO.PERIODOUNIVERSIDAD.PEUN_PERIODO HAVING (((ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO)='ABIERTA') AND ((ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ESTADOADMISION)='INSCRITO') AND ((ACADEMICO.PROGRAMAXFORMULARIO.PRXF_PRIORIDAD)='1')) ORDER BY PROG_NOMBRE, NOMBRE, JORN_DESCRIPCION";
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        while (OCIFetch($query))
        {
            $fila = array(
                "ASPI_ID" => ociresult($query, "ASPI_ID"),
                "FOIN_ID" => ociresult($query, "FOIN_ID"),
                "ASPI_NUMERODOCUMENTO" => ociresult($query, "ASPI_NUMERODOCUMENTO"),
                "PEUN_ANO" => ociresult($query, "PEUN_ANO"),
                "PEUN_PERIODO" => ociresult($query, "PEUN_PERIODO"),
                "NOMBRE" => ociresult($query, "NOMBRE"),
                "PROG_ID" => ociresult($query, "PROG_ID"),
                "PROG_NOMBRE" => ociresult($query, "PROG_NOMBRE"),
                "METO_DESCRIPCION" => ociresult($query, "METO_DESCRIPCION"),
                "JORN_DESCRIPCION" => ociresult($query, "JORN_DESCRIPCION")
            );
            array_push($resultados, $fila);
        }
        echo utf8_encode('{"datos": ' . json_encode($resultados) . '}');
        OCILogoff($conn);
    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }
}

//Insertar en Tabla ENTREVISTANEW
function InsertarEntrevista(){
    $request = Slim::getInstance()->request();
    $entrevista = json_decode($request->getBody());
    //echo utf8_encode('{"datos": ' . json_encode($entrevista) . '}');
    try{
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "INSERT INTO ACADEMICO.ENTREVISTANEW (ENTRE_ID, FOIN_ID, ENTRE_FECHA, USUA_ID, ENTRE_PREGUNTA1, ENTRE_PREGUNTA2, ENTRE_PREGUNTA3, ENTRE_PREGUNTA4, ENTRE_PREGUNTA5, ENTRE_HOMOLOGACION, ENTRE_OBSERVACIONES) VALUES(".$entrevista->FOIN_ID.",".$entrevista->FOIN_ID.",TO_DATE('".$entrevista->FECHAENTREVISTA_."','DD/MM/RRRR'),".$entrevista->USUA_ID.",'".$entrevista->PREGUNTA1."','".$entrevista->PREGUNTA2."','".$entrevista->PREGUNTA3."','".$entrevista->PREGUNTA4."','".$entrevista->PREGUNTA5."',".$entrevista->HOMOLOGACION.",'".$entrevista->OBSERVACIONES."')";
        //echo utf8_encode('{"datos": ' . json_encode($sql) . '}');
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        OCICommit($conn);
        OCILogoff($conn);
        echo '{"mensaje: ":"ExitoEntrevista"}';
    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }
}

function BuscarLlamado($PROG_ID2){
    try{
        $resultados = array();
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "SELECT ACADEMICO.LLAMADO.LLAM_ID, ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO, ACADEMICO.UNIDADPROGRAMA.PROG_ID FROM ((ACADEMICO.LLAMADO INNER JOIN ACADEMICO.CONVOCATORIAINSCRIPCION ON ACADEMICO.LLAMADO.COIN_ID = ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ID) INNER JOIN ACADEMICO.UNIDADPROGRAMA ON ACADEMICO.CONVOCATORIAINSCRIPCION.UNPR_ID = ACADEMICO.UNIDADPROGRAMA.UNPR_ID) INNER JOIN ACADEMICO.PROGRAMA ON ACADEMICO.UNIDADPROGRAMA.PROG_ID = ACADEMICO.PROGRAMA.PROG_ID WHERE (((ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO)='ABIERTA') AND ((ACADEMICO.UNIDADPROGRAMA.PROG_ID)=".$PROG_ID2."))";
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        while (OCIFetch($query))
        {
            $fila = array(
                "LLAM_ID" => ociresult($query, "LLAM_ID")
            );
            array_push($resultados, $fila);
        }
        echo utf8_encode('{"datos": ' . json_encode($resultados) . '}');
        OCILogoff($conn);
    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }
}
