<?php
//Buscar existe aspirante
function ListarPreinscritos(){
    try{
        $resultados = array();
        $conexion = new conexionBD();
        $conn = $conexion->conectar();
        $sql = "SELECT ACADEMICO.ASPIRANTE.ASPI_ID, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID, ACADEMICO.ASPIRANTE.ASPI_NUMERODOCUMENTO, ACADEMICO.ASPIRANTE.ASPI_PRIMERAPELLIDO||' '|| ACADEMICO.ASPIRANTE.ASPI_SEGUNDOAPELLIDO ||' '|| ACADEMICO.ASPIRANTE.ASPI_PRIMERNOMBRE ||' '|| ACADEMICO.ASPIRANTE.ASPI_SEGUNDONOMBRE as NOMBRE, ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO, ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ESTADOADMISION, ACADEMICO.PROGRAMA.PROG_ID ,ACADEMICO.PROGRAMA.PROG_NOMBRE, ACADEMICO.METODOLOGIA.METO_DESCRIPCION, ACADEMICO.PROGRAMAXFORMULARIO.PRXF_PRIORIDAD, ACADEMICO.JORNADANEW.JORN_DESCRIPCION FROM (((ACADEMICO.CIRCUNSCRIPCIONXUNIDADPROGRAMA INNER JOIN ACADEMICO.CONVOCATORIAINSCRIPCION ON ACADEMICO.CIRCUNSCRIPCIONXUNIDADPROGRAMA.COIN_ID = ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ID) INNER JOIN ((((ACADEMICO.PROGRAMAXFORMULARIO INNER JOIN ACADEMICO.FORMULARIOINSCRIPCION ON ACADEMICO.PROGRAMAXFORMULARIO.FOIN_ID = ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ID) INNER JOIN (ACADEMICO.ASPIRANTE INNER JOIN ACADEMICO.CIRCUNSCRIPCION ON ACADEMICO.ASPIRANTE.CIRC_ID = ACADEMICO.CIRCUNSCRIPCION.CIRC_ID) ON ACADEMICO.FORMULARIOINSCRIPCION.ASPI_ID = ACADEMICO.ASPIRANTE.ASPI_ID) INNER JOIN ACADEMICO.UNIDADPROGRAMA ON ACADEMICO.PROGRAMAXFORMULARIO.UNPR_ID = ACADEMICO.UNIDADPROGRAMA.UNPR_ID) INNER JOIN ACADEMICO.PROGRAMA ON ACADEMICO.UNIDADPROGRAMA.PROG_ID = ACADEMICO.PROGRAMA.PROG_ID) ON (ACADEMICO.CONVOCATORIAINSCRIPCION.UNPR_ID = ACADEMICO.UNIDADPROGRAMA.UNPR_ID) AND (ACADEMICO.CIRCUNSCRIPCIONXUNIDADPROGRAMA.CIRC_ID = ACADEMICO.CIRCUNSCRIPCION.CIRC_ID)) INNER JOIN ACADEMICO.METODOLOGIA ON ACADEMICO.PROGRAMA.METO_ID = ACADEMICO.METODOLOGIA.METO_ID) INNER JOIN ACADEMICO.JORNADANEW ON ACADEMICO.PROGRAMAXFORMULARIO.JORN_ID=ACADEMICO.JORNADANEW.JORN_ID WHERE (((ACADEMICO.CONVOCATORIAINSCRIPCION.COIN_ESTADO)='ABIERTA') AND ((ACADEMICO.FORMULARIOINSCRIPCION.FOIN_ESTADOADMISION)='PREINSCRITO') AND ((ACADEMICO.PROGRAMAXFORMULARIO.PRXF_PRIORIDAD)='1'))";
        $query =OCIParse($conn, $sql);
        OCIExecute($query, OCI_DEFAULT);
        while (OCIFetch($query))
        {
            $fila = array(
                "ASPI_ID" => ociresult($query, "ASPI_ID"),
                "FOIN_ID" => ociresult($query, "FOIN_ID"),
                "ASPI_NUMERODOCUMENTO" => ociresult($query, "ASPI_NUMERODOCUMENTO"),
                //"ASPI_PRIMERAPELLIDO" => ociresult($query, "ASPI_PRIMERAPELLIDO"),
                //"ASPI_SEGUNDOAPELLIDO" => ociresult($query, "ASPI_SEGUNDOAPELLIDO"),
                //"ASPI_PRIMERNOMBRE" => ociresult($query, "ASPI_PRIMERNOMBRE"),
                //"ASPI_SEGUNDONOMBRE" => ociresult($query, "ASPI_SEGUNDONOMBRE"),
                "NOMBRE" => ociresult($query, "NOMBRE"),
                "PROG_ID" => ociresult($query, "PROG_ID"),
                "PROG_NOMBRE" => ociresult($query, "PROG_NOMBRE"),
                "METO_DESCRIPCION" => ociresult($query, "METO_DESCRIPCION"),
                "JORN_DESCRIPCION" => ociresult($query, "JORN_DESCRIPCION")
            );
            array_push($resultados, $fila);
        }
        echo utf8_encode('{"datos": ' . json_encode($resultados) . '}');
        OCILogoff($conn);
    }
    catch(Exception $e){
        OCILogoff($conn);
        echo '{"error: ":' . $e->getMessage() . '}';
    }
}